version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: talklens_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth:
    image: talklens-auth:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_DB=talklens_auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres

  collector:
    build:
      context: .
      dockerfile: TalkLens.Collector.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_DB=talklens_auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - Jwt__Secret=your-256-bit-secret-your-256-bit-secret-your-256-bit-secret
      - Jwt__Issuer=talklens-auth
      - Jwt__Audience=talklens-collector
    ports:
      - "5001:80"
    depends_on:
      - postgres
      - auth

volumes:
  postgres_data: 